# Generated by Django 3.0 on 2022-04-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('empName', models.CharField(max_length=5000)),
                ('empDOJ', models.DateField(auto_now_add=True)),
                ('empDescription', models.CharField(max_length=5000)),
                ('empCategory', models.CharField(max_length=5000)),
                ('empCity', models.CharField(max_length=5000)),
                ('empOfficeVenue', models.CharField(max_length=5000)),
            ],
        ),
    ]
