# Generated by Django 3.0 on 2022-03-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=5000)),
                ('last_name', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=5000, unique=True)),
                ('job_role', models.CharField(max_length=5000)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
